# Generated by Django 5.1.6 on 2025-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('first', 'Первые блюда'), ('second', 'Вторые блюда'), ('drinks', 'Напитки'), ('desserts', 'Десерты'), ('bakery', 'Выпечка')], default='drinks', max_length=20, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Изображение блюда'),
        ),
    ]
