# Generated by Django 5.1.6 on 2025-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dish_category_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('first', 'Первые блюда'), ('second', 'Вторые блюда'), ('salad', 'Салаты'), ('drinks', 'Напитки'), ('desserts', 'Десерты'), ('bakery', 'Выпечка')], default='drinks', max_length=20, verbose_name='Категория блюда'),
        ),
    ]
